const deploymentActions = {
  UPDATE_CAMPAIGN_VALUES: 'UPDATE_CAMPAIGN_VALUES',
  RUN_UNSTARTED: 'RUN_UNSTARTED',
  RUN_IN_PROGRESS: 'RUN_IN_PROGRESS',
  RUN_COMPLETE: 'RUN_COMPLETE',
  RUN_ERROR: 'RUN_ERROR',
  DEPLOYMENT_COMPLETE: 'DEPLOYMENT_COMPLETE'
};

module.exports = deploymentActions;
