const deploymentActions = {
  UPDATE_CAMPAIGN_VALUES: 'UPDATE_CAMPAIGN_VALUES',
  RUN_UNSTARTED: 'RUN_UNSTARTED',
  RUN_IN_PROGRESS: 'RUN_IN_PROGRESS',
  RUN_COMPLETE: 'RUN_COMPLETE',
  RUN_ERROR: 'RUN_ERROR',
  DEPLOYMENT_COMPLETE: 'DEPLOYMENT_COMPLETE',
  SET_DEPLOYMENT_RESULTS: 'SET_DEPLOYMENT_RESULTS'
};

module.exports = deploymentActions;
